Initialize One to One Chat When Message Sent
timeless-space/stream-chat-swift pull request #86
Opened 2022-05-20 13:18 UTC by jitendra-simform

### 🔗 Issue Links

https://docs.google.com/document/d/1wjuu7kaHxSsR2MGvJUQ_Mz3tjoQsbx46QKDUjdku3uU/edit

### 🎯  Fixed Bug

We should not allow for blank 1-1 chats ,I.e., once 1-1 chat is created, the cursor should be put on the text field; if user exits out w/o typing anything, this chat should no longer be listed in the chat list

2022-06-01 06:51 UTC, ajay-simform requested changes

2022-06-01 06:51 UTC, ajay-simform commented on Sources/StreamChatUI/Composer/ComposerVC.swift
> +            break
@jitendra-simform  `break` is not required here

2022-06-01 13:45 UTC, parth-simformsolutions commented on Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
> +        guard let currentUserId = ChatClient.shared.currentUserId else { return }
@jitendra-simform  we should combine this two condition in one guard condition.

2022-06-22 06:18 UTC, jitendra-simform commented
Issue got fixed in latest stream chat sdk

2022-06-22 06:18 UTC, closed without merging