NF- 1252 wallet photo collections viewer
timeless-space/stream-chat-swift pull request #93
Opened 2022-05-26 11:28 UTC by parth-simformsolutions

### 🔗 Issue Links

_Provide all Jira tickets and/or Github issues related to this PR, if applicable._

### 🎯 Goal

_Describe why we are making this change._

### 📝 Summary

_Provide bullet points with the most important changes in the codebase._

### 🛠 Implementation

_Provide a detailed description of the implementation and explain your decisions if you find them relevant._

### 🎨 Showcase

_Add relevant screenshots and/or videos/gifs to easily see what this PR changes, if applicable._

| Before | After |
| ------ | ----- |
|  img   |  img  |

### 🧪 Manual Testing Notes

_Explain how this change can be tested manually, if applicable._

### ☑️ Contributor Checklist
- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] This change follows zero ⚠️ policy (required)
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

### 🎁 Meme

_Provide a funny gif or image that relates to your work on this pull request. (Optional)_

2022-05-26 13:36 UTC, jitendra-simform commented on Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
> +    private func isImagePreview(_ message: ChatMessage?) -> Bool {
@parth-simformsolutions  it is more convenient if you add this method to ChatMessage class inside extension , thanks

2022-06-17 15:19 UTC, ajay-simform requested changes

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChat/Models/ChatMessage.swift
> +    public var isMultiplePreview: Bool {
@parth-simformsolutions  The variable name should be descriptive.

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChatUI/ChatMessageList/Attachments/VideoAttachmentGalleryPreview.swift
> +    open lazy var imageView = UIImageView()
@parth-simformsolutions  Please change to private(set)

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChatUI/ChatMessageList/ChatMessage/AttachmentPreviewBubble.swift
> +    var isSender = false
@parth-simformsolutions  isSender is not in use

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChatUI/ChatMessageList/ChatMessage/AttachmentPreviewBubble.swift
> +            imageTask = Components.default.imageLoader.loadImage(
@parth-simformsolutions  is imageTask required here?

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChatUI/ChatMessageList/ChatMessage/PhotoCollectionBubble.swift
> +    var isSender = false
@parth-simformsolutions  please remove isSender if not required

2022-06-17 15:19 UTC, ajay-simform commented on Sources/StreamChatUI/Utils/StackedItems/StackedItem.swift
> +    public static func staticData() -> [StackedItem] {
@parth-simformsolutions  Please remove this function if it is not required.

2022-06-21 13:50 UTC, ajay-simform approved these changes

2022-07-01 04:54 UTC, merged